### ISSUE TITLE
Add Widget as another example in Addressing examples

### ISSUE THREAD

**Issue by davidccf** [w3c/miniapp-addressing#6]
As MiniApp Widget is a special form of MiniApp Page, it is recommended to add Widget as another example in Addressing examples. For instance, in Section 4, MiniApp URI examples.

**Comment by maxie** [comment]
In addition to Widget, the path of MiniApp page could be something other than /pages. So, it's better to add more examples about pages in other path.

**Comment by Sharonzd** [comment]
Thank you for your comments. I have added the widgets path to [the example in Section 4](https://w3c.github.io/miniapp-addressing/#example-miniapp-uri-examples).
But I didn't add more pages examples, Because the path is not a constant, it can be anything.
'pages' or 'widgets' is just equivalent to foo or bar. 
And the path resolver should be specified in the MiniApp Packaging spec.
